Drone setup
easv-devops/Climate pull request #28
Opened 2024-05-01 20:00 UTC by micdra01

2024-05-02 07:40 UTC, JennyTromTheBlock requested changes
Syper kode, det kan godt blive lidt tungt når der er så mange ændringer i imports. Jeg kan se at test er bundet op på vores produktion database, hvilket bliver et problem med flyway scheme history, når man sletter og opretter tables udenom flyway.

Jeg vil foreslå at gøre programmet klar til at tage imod en conn string til vores db i main metoden

2024-05-06 12:32 UTC, steffaneckeroth approved these changes
Det ser fint ud af test kører på sin egen DB. Fin implementering af async af keyvault.

2024-05-06 12:35 UTC, steffaneckeroth approved these changes

2024-05-06 12:36 UTC, JennyTromTheBlock approved these changes

2024-05-06 12:37 UTC, merged